### ISSUE TITLE
CRC32 in SDK 1.30

### ISSUE THREAD

**Issue by atwoz** [nqd/esp8266-dev#6]
Hello Nguyễn, SDK 1.30 is out and Espressif added a new cool feature (which is really important) to the OTA update methos. A CRC32 was added to the SDK, I believe the update methods verify the CRC32 once the full file is downloaded and it should return error if the CRC32 does not match. To calculate and modify the binary files to include the CRC32, Espressif added a python script. 

It would be great if your makefile could include the extra step to add this CRC32 to the binary by using the python script from Espressif. Thanks.

**Comment by atwoz** [comment]
Actually, I believe there is not much to be done, just to replace the gen_appbin.py in the sdk repo as well as adding the new 1.30 SDK files.

**Comment by nqd** [comment]
Great thanks. I will update when come back from traveling. ---- On Sun, 09 Aug 2015 23:08:37 +0700  atwoznotifications@github.com wrote ----Actually, I believe there is not much to be done, just to replace the gen_appbin.py in the sdk repo as well as adding the new 1.30 SDK files.—Reply to this email directly or view it on GitHub.

**Comment by nqd** [comment]
Need to figure out why when with sdk 1.3.0 ESP cannot connect to AP at the first hand. Something happens with the radio part that need to be solved before update.
