### ISSUE TITLE
ESP07 8MBit error magic! when upgrade

### ISSUE THREAD

**Issue by LinhDNguyen** [nqd/esp8266-dev#7]
Hi Dinh,

Firstly, many thank for you contribution.

I have update the Makefile.common to support 8MBit flash then try OTA update following your Readme.md instructions. But I have got following log at 74880 baudrate

```2nd boot version : 1.4(b1)
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size & Map: 8Mbit(512KB+512KB)
jump to run user1 @ 1000

error magic!
backup boot failed.

user code done```

I also got this problem with original SDK 1.1, 1.2 and 1.3. Do you have any idea about this? Thank so much.

**Comment by nqd** [comment]
Seems that you flash it right (512KB+512KB). What linker did you use. And if you dont mind, post your make here.

**Comment by LinhDNguyen** [comment]
Hi, You can check at commit 2b201dd344555e976d6258421c80efbd267a8282 of my repo (https://github.com/nvl1109/esp8266-dev)
The linker is eagle.app.v6.new.1024.app1.ld (LD_SCRIPT = eagle.app.v6.new.$(flash).app$(IMAGE).ld)
